using System.Drawing;  // Color (Primitives) — used only to compare against Color.Empty and read R/G/B.
using System.Text;

namespace FBEditor.Core;

/// <summary>
/// Generates FreeBASIC + Window9 source code from a W9FormDesign model.
/// Produces clean, well-structured .bas files (enum IDs, proportional resize, event loop).
/// Ported from Modules/W9CodeGenerator.vb (VB Module -> C# static class).
/// </summary>
public static class W9CodeGenerator
{
    // Line-ending separators used when splitting multi-line property text (Items, TabNames).
    // Replaces VB's vbCrLf / vbLf / vbCr constants.
    private static readonly string[] LineSeparators = { "\r\n", "\n", "\r" };

    /// <summary>Generate complete FreeBASIC source from a form design.</summary>
    public static string GenerateCode(W9FormDesign design)
    {
        var sb = new StringBuilder();

        EmitHeader(sb, design);
        sb.AppendLine();

        EmitIncludes(sb);
        sb.AppendLine();

        if (design.ProportionalResize)
        {
            EmitScalingConstants(sb, design);
            sb.AppendLine();
        }

        EmitLinuxCompat(sb);
        sb.AppendLine();

        EmitGadgetEnum(sb, design);
        sb.AppendLine();

        if (design.MenuItems.Count > 0)
        {
            EmitMenuEnum(sb, design);
            sb.AppendLine();
        }

        if (design.HasKeyboardShortcut)
        {
            EmitShortcutEnum(sb, design);
            sb.AppendLine();
        }

        EmitSharedVars(sb, design);
        sb.AppendLine();

        EmitEventHandlerStubs(sb, design);
        sb.AppendLine();

        if (design.ProportionalResize && design.HandleResize)
        {
            EmitResizeHandler(sb, design);
            sb.AppendLine();
        }

        EmitMainSection(sb, design);
        sb.AppendLine();

        EmitEventLoop(sb, design);
        sb.AppendLine();

        EmitHelperReference(sb, design);

        return sb.ToString();
    }

    // =========================================================================
    // Section emitters
    // =========================================================================

    /// <summary>Generate code for a multi-form project.</summary>
    public static string GenerateMultiFormCode(W9FormProject project)
    {
        if (project is null || project.Forms.Count == 0) return "";

        // Single form — delegate to original generator
        if (project.Forms.Count == 1)
            return GenerateCode(project.Forms[0]);

        // ----- Multi-form generation -----
        var sb = new StringBuilder();
        var main = project.MainForm!; // Forms.Count >= 2 here, so MainForm is non-null

        // File header
        sb.AppendLine("' ============================================================================");
        sb.AppendLine("' " + main.FormTitle + " - FreeBASIC + Window9 (Multi-Form)");
        sb.AppendLine("' ============================================================================");
        sb.AppendLine("' Generated by FBEditor v5.3.0 Visual Form Designer");
        sb.AppendLine("' Date: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm"));
        sb.AppendLine("' Forms: " + project.Forms.Count);
        foreach (var f in project.Forms)
            sb.AppendLine("'   " + f.VarName + " — " + f.FormTitle +
                          (f.FormType == W9FormType.MainForm ? " (main)" : " (child)"));
        sb.AppendLine("' ============================================================================");
        sb.AppendLine("' Compile: fbc -s gui " + SanitizeFilename(main.FormTitle) + ".bas");
        sb.AppendLine("' ============================================================================");
        sb.AppendLine();

        EmitIncludes(sb);
        sb.AppendLine();

        // Scaling macros (use main form's base dimensions)
        bool anyResize = project.Forms.Any(f => f.ProportionalResize);
        if (anyResize)
        {
            EmitScalingConstants(sb, main);
            sb.AppendLine();
        }

        EmitLinuxCompat(sb);
        sb.AppendLine();

        // Unified GadgetID enum (all gadgets from all forms)
        sb.AppendLine("' --- Gadget IDs (all forms) ---");
        sb.AppendLine("Enum GadgetID");
        sb.AppendLine("  giFirst = " + main.GadgetEnumStart);

        // Deduplicate enum names across all forms
        var usedNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var f in project.Forms)
        {
            if (f.Gadgets.Count > 0)
            {
                sb.AppendLine("  ' -- " + f.VarName + ": " + f.FormTitle + " --");
                foreach (var g in f.Gadgets)
                {
                    if (!string.IsNullOrEmpty(g.EnumName))
                    {
                        // If this name is already used, generate a unique one
                        if (usedNames.Contains(g.EnumName))
                            g.EnumName = W9GadgetRegistry.GenerateUniqueEnumName(g.GadgetType, usedNames);
                        usedNames.Add(g.EnumName);
                        sb.AppendLine("  " + g.EnumName);
                    }
                }
            }
        }
        sb.AppendLine("End Enum");
        sb.AppendLine();

        // Menu enum (from all forms that have menus)
        bool anyMenus = project.Forms.Any(f => f.MenuItems.Count > 0);
        if (anyMenus)
        {
            sb.AppendLine("' --- Menu IDs ---");
            sb.AppendLine("Enum MenuID");
            sb.AppendLine("  miFirst = " + main.MenuEnumStart);
            foreach (var f in project.Forms)
                foreach (var topMenu in f.MenuItems)
                {
                    if (!string.IsNullOrEmpty(topMenu.EnumName))
                        sb.AppendLine("  " + topMenu.EnumName);
                    foreach (var child in topMenu.Children)
                        if (!string.IsNullOrEmpty(child.EnumName))
                            sb.AppendLine("  " + child.EnumName);
                }
            sb.AppendLine("End Enum");
            sb.AppendLine();
        }

        // Shortcut enum
        bool anyShortcuts = project.Forms.Any(f => f.HasKeyboardShortcut);
        if (anyShortcuts)
        {
            EmitShortcutEnum(sb, main);
            sb.AppendLine();
        }

        // Shared variables — all HWND handles
        sb.AppendLine("' --- Shared variables ---");
        foreach (var f in project.Forms)
            sb.AppendLine("Dim As HWND " + f.VarName);
        sb.AppendLine("Dim As Integer event");
        if (anyMenus)
        {
            sb.Append("Dim Shared As HMENU hMenu");
            foreach (var f in project.Forms)
                foreach (var topMenu in f.MenuItems)
                {
                    string varName = "h" + SanitizeVarName(topMenu.Text) + "Menu";
                    sb.Append(", " + varName);
                }
            sb.AppendLine();
        }
        bool anyTimer = project.Forms.Any(f => f.HasTimer);
        if (anyTimer)
            sb.AppendLine("Dim Shared As Integer Timer1");
        sb.AppendLine();

        // Event handler stubs (from all forms)
        foreach (var f in project.Forms)
        {
            var eventGadgets = new List<W9GadgetInstance>();
            foreach (var g in f.Gadgets)
            {
                if (g.GadgetType == W9GadgetType.Button)
                    eventGadgets.Add(g);
                else if (g.OnClickEvent || g.OnChangeEvent || g.OnDoubleClickEvent)
                    eventGadgets.Add(g);
            }
            if (eventGadgets.Count > 0)
            {
                EmitEventHandlerStubs(sb, f);
                sb.AppendLine();
            }
        }

        // Resize handlers — one per form that has proportional resize
        foreach (var f in project.Forms)
        {
            if (f.ProportionalResize && f.HandleResize && f.Gadgets.Count > 0)
            {
                string subName = GetResizeSubName(f);
                sb.AppendLine("' ============================================================================");
                sb.AppendLine("' " + subName + " - Resize handler for " + f.VarName + " (" + f.FormTitle + ")");
                sb.AppendLine("' ============================================================================");
                sb.AppendLine("Sub " + subName + "(WinWid As Long, WinHei As Long)");

                foreach (var g in f.Gadgets)
                {
                    if (g.GadgetType == W9GadgetType.StatusBar) continue;
                    sb.AppendLine("  ResizeGadget(" + g.EnumName + ", ScaleX(" + g.X + "), ScaleY(" + g.Y + "), ScaleX(" + g.W + "), ScaleY(" + g.H + "))");
                    if (g.GadgetType == W9GadgetType.Editor)
                    {
                        if (g.IsReadOnly) sb.AppendLine("  ReadOnlyEditor(" + g.EnumName + ", 1)");
                        if (g.WordWrap) sb.AppendLine("  SetTransferTextLineEditorGadget(" + g.EnumName + ", 1)");
                    }
                }
                sb.AppendLine();
                sb.AppendLine("  ' --- Scale fonts proportionally ---");
                foreach (var g in f.Gadgets)
                {
                    if (g.GadgetType == W9GadgetType.StatusBar) continue;
                    var tdef = W9GadgetRegistry.GetTypeDef(g.GadgetType);
                    if (tdef != null && tdef.SupportsFont)
                    {
                        string fontName = string.IsNullOrEmpty(g.FontName) ? "Consolas" : g.FontName;
                        int fontSize = g.FontSize > 0 ? g.FontSize : 11;
                        sb.AppendLine("  SetGadgetFont(" + g.EnumName + ", Cint(LoadFont(\"" + fontName + "\", ScaleY(" + fontSize + "))))");
                    }
                }
                sb.AppendLine();
                sb.AppendLine("  UpdateInfoXserver()");
                sb.AppendLine("End Sub");
                sb.AppendLine();
            }
        }

        // === MAIN SECTION: Create all forms and gadgets ===
        sb.AppendLine("' ============================================================================");
        sb.AppendLine("' MAIN - Create windows and gadgets");
        sb.AppendLine("' ============================================================================");
        sb.AppendLine();

        // Create child forms FIRST (they're typically hidden initially)
        foreach (var f in project.Forms)
        {
            if (f.FormType == W9FormType.ChildForm)
            {
                EmitFormCreation(sb, f);
                sb.AppendLine();
            }
        }

        // Create main form
        EmitFormCreation(sb, main);
        sb.AppendLine();

        // Timer on main form
        if (main.HasTimer)
        {
            sb.AppendLine("' --- Timer ---");
            sb.AppendLine("SetTimer(hMainForm, Timer1, " + main.TimerInterval + ", NULL)");
            sb.AppendLine();
        }

        // Keyboard shortcuts
        foreach (var f in project.Forms)
            if (f.HasKeyboardShortcut)
                sb.AppendLine("AddKeyboardShortcut(" + f.VarName + ", FVIRTKEY, VK_RETURN, siDefKey)");

        sb.AppendLine();
        sb.AppendLine("UpdateInfoXserver()");
        sb.AppendLine();

        // Initial resize for main form
        if (main.ProportionalResize)
        {
            sb.AppendLine("' Force initial layout");
            sb.AppendLine(GetResizeSubName(main) + "(WindowWidth(hMainForm), WindowHeight(hMainForm))");
        }
        sb.AppendLine();

        // === EVENT LOOP ===
        sb.AppendLine("' ============================================================================");
        sb.AppendLine("' EVENT LOOP");
        sb.AppendLine("' ============================================================================");
        sb.AppendLine("Do");
        sb.AppendLine("    Select Case WaitEvent()");
        sb.AppendLine();

        // Resize events — dispatch by EventHwnd
        var resizeForms = project.Forms.Where(f => f.ProportionalResize && f.HandleResize && f.Gadgets.Count > 0).ToList();
        if (resizeForms.Count > 0)
        {
            sb.AppendLine("    Case EventSize");
            foreach (var f in resizeForms)
            {
                sb.AppendLine("        If EventHwnd = " + f.VarName + " Then");
                sb.AppendLine("            " + GetResizeSubName(f) + "(WindowWidth(" + f.VarName + "), WindowHeight(" + f.VarName + "))");
                sb.AppendLine("        End If");
            }
            sb.AppendLine();
        }

        // Menu events
        if (anyMenus || anyShortcuts)
        {
            sb.AppendLine("    Case EventMenu");
            sb.AppendLine("        Select Case EventNumber");
            if (anyShortcuts)
            {
                var defaultBtn = main.Gadgets.Find(g => g.ID == main.DefaultButtonID);
                if (defaultBtn != null)
                {
                    string handlerName = SanitizeVarName(defaultBtn.EnumName.Replace("gi", "On")) + "Click";
                    sb.AppendLine("        Case siDefKey");
                    sb.AppendLine("            " + handlerName + "()");
                }
                else
                {
                    sb.AppendLine("        Case siDefKey");
                    sb.AppendLine("            ' TODO: Handle Enter key");
                }
            }
            foreach (var f in project.Forms)
                foreach (var topMenu in f.MenuItems)
                    foreach (var child in topMenu.Children)
                        if (!child.IsSeparator)
                        {
                            sb.AppendLine("        Case " + child.EnumName);
                            sb.AppendLine("            ' TODO: Handle " + child.Text);
                        }
            sb.AppendLine("        End Select");
            sb.AppendLine();
        }

        // Timer event
        if (anyTimer)
        {
            sb.AppendLine("    Case EventTimer");
            sb.AppendLine("        ' TODO: Handle timer tick");
            sb.AppendLine();
        }

        // Close event — multi-form dispatch
        sb.AppendLine("    Case EventClose");
        var childForms = project.Forms.Where(f => f.FormType == W9FormType.ChildForm).ToList();
        if (childForms.Count > 0)
        {
            foreach (var f in childForms)
            {
                sb.AppendLine("        If EventHwnd() = " + f.VarName + " Then");
                if (f.HideOnClose)
                    sb.AppendLine("            HideWindow(" + f.VarName + ", 1)  ' Hide instead of close");
                else
                    sb.AppendLine("            ' TODO: Handle " + f.VarName + " close");
                sb.AppendLine("        Else");
            }
            // Main form close — end application
            if (main.HasTimer)
                sb.AppendLine("            KillTimer(hMainForm, Timer1)");
            sb.AppendLine("            End");
            // Close all the Else/End If from child forms
            foreach (var f in childForms)
                sb.AppendLine("        End If");
        }
        else
        {
            if (main.HasTimer)
                sb.AppendLine("        KillTimer(hMainForm, Timer1)");
            sb.AppendLine("        End");
        }
        sb.AppendLine();

        // Gadget events (from all forms)
        var allClickGadgets = project.AllGadgets().FindAll(g =>
            g.GadgetType == W9GadgetType.Button || g.OnClickEvent || g.OnChangeEvent || g.OnDoubleClickEvent);
        if (allClickGadgets.Count > 0)
        {
            sb.AppendLine("    Case EventGadget");
            sb.AppendLine("        Select Case EventNumber");
            foreach (var g in allClickGadgets)
            {
                string baseName = SanitizeVarName(g.EnumName.Replace("gi", ""));
                sb.AppendLine("        Case " + g.EnumName);
                if ((g.GadgetType == W9GadgetType.Button || g.OnClickEvent) && !g.OnChangeEvent && !g.OnDoubleClickEvent)
                    sb.AppendLine("            On" + baseName + "Click()");
                else if (g.OnClickEvent && g.OnChangeEvent)
                {
                    sb.AppendLine("            On" + baseName + "Click()");
                    sb.AppendLine("            On" + baseName + "Change()");
                }
                else if (g.OnChangeEvent && !g.OnClickEvent)
                    sb.AppendLine("            On" + baseName + "Change()");
                else if (g.GadgetType == W9GadgetType.Button)
                    sb.AppendLine("            On" + baseName + "Click()");

                if (g.OnDoubleClickEvent)
                    sb.AppendLine("            ' On" + baseName + "DoubleClick()");
            }
            sb.AppendLine("        End Select");
            sb.AppendLine();
        }

        sb.AppendLine("    End Select");
        sb.AppendLine("Loop");
        sb.AppendLine();

        // Helper reference (combined from all forms)
        EmitHelperReference(sb, main);

        return sb.ToString();
    }

    /// <summary>Emit creation code for a single form and its gadgets.</summary>
    private static void EmitFormCreation(StringBuilder sb, W9FormDesign f)
    {
        string label = f.FormType == W9FormType.MainForm ? "main window" : "child window";
        sb.AppendLine("' --- Create " + label + ": " + f.VarName + " ---");
        sb.AppendLine(f.VarName + " = OpenWindow(\"" + EscapeString(f.FormTitle) + "\", " +
                      f.FormX + ", " + f.FormY + ", " +
                      f.FormWidth + ", " + f.FormHeight + ")");
        if (f.CenterOnScreen)
            sb.AppendLine("CenterWindow(" + f.VarName + ")");
        if (f.FormColor != Color.Empty)
            sb.AppendLine("WindowColor(" + f.VarName + ", BGR(" + f.FormColor.R + ", " +
                          f.FormColor.G + ", " + f.FormColor.B + "))");

        // Create menus for this form
        if (f.MenuItems.Count > 0)
            EmitMenuCreation(sb, f);

        // Create gadgets for this form
        if (f.Gadgets.Count > 0)
            foreach (var g in f.Gadgets)
                EmitGadgetCreation(sb, g);

        // Hide child forms that start hidden
        if (f.StartHidden)
            sb.AppendLine("HideWindow(" + f.VarName + ", 1)  ' Start hidden — show with HideWindow(" + f.VarName + ", 0)");
    }

    /// <summary>Get a unique resize sub name for a form.</summary>
    private static string GetResizeSubName(W9FormDesign f)
    {
        if (f.FormType == W9FormType.MainForm) return "size_change";
        return "resize_" + SanitizeVarName(f.VarName.Replace("h", "").ToLower());
    }

    private static void EmitHeader(StringBuilder sb, W9FormDesign design)
    {
        sb.AppendLine("' ============================================================================");
        sb.AppendLine("' " + design.FormTitle + " - FreeBASIC + Window9");
        sb.AppendLine("' ============================================================================");
        sb.AppendLine("' Generated by FBEditor v5.3.0 Visual Form Designer");
        sb.AppendLine("' Date: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm"));
        sb.AppendLine("' ============================================================================");
        sb.AppendLine("' Compile: fbc -s gui " + SanitizeFilename(design.FormTitle) + ".bas");
        sb.AppendLine("' ============================================================================");
    }

    private static void EmitIncludes(StringBuilder sb)
    {
        sb.AppendLine("#Ifdef __FB_LINUX__");
        sb.AppendLine("#Undef MAKELONG");
        sb.AppendLine("#Endif");
        sb.AppendLine();
        sb.AppendLine("#Include \"window9.bi\"");
    }

    private static void EmitScalingConstants(StringBuilder sb, W9FormDesign design)
    {
        sb.AppendLine("' --- Base dimensions for proportional scaling ---");
        sb.AppendLine("Dim Shared As Long BaseWidth  : BaseWidth  = " + design.BaseWidth);
        sb.AppendLine("Dim Shared As Long BaseHeight : BaseHeight = " + design.BaseHeight);
        sb.AppendLine();
        sb.AppendLine("#Define ScaleX(_V) ((((_V) * WinWid) \\ BaseWidth))");
        sb.AppendLine("#Define ScaleY(_V) ((((_V) * WinHei) \\ BaseHeight))");
    }

    private static void EmitLinuxCompat(StringBuilder sb)
    {
        sb.AppendLine("' --- Linux compatibility ---");
        sb.AppendLine("#Ifndef BS_DEFPUSHBUTTON");
        sb.AppendLine("  #Define BS_DEFPUSHBUTTON 0");
        sb.AppendLine("#Endif");
        sb.AppendLine("#Ifndef SS_CENTERIMAGE");
        sb.AppendLine("  #Define SS_CENTERIMAGE 0");
        sb.AppendLine("#Endif");
        sb.AppendLine("#Ifndef SS_NOTIFY");
        sb.AppendLine("  #Define SS_NOTIFY 0");
        sb.AppendLine("#Endif");
    }

    private static void EmitGadgetEnum(StringBuilder sb, W9FormDesign design)
    {
        sb.AppendLine("' --- Gadget IDs ---");
        sb.AppendLine("Enum GadgetID");
        sb.AppendLine("  giFirst = " + design.GadgetEnumStart);
        foreach (var g in design.Gadgets)
            if (!string.IsNullOrEmpty(g.EnumName))
                sb.AppendLine("  " + g.EnumName);
        sb.AppendLine("End Enum");
    }

    private static void EmitMenuEnum(StringBuilder sb, W9FormDesign design)
    {
        sb.AppendLine("' --- Menu IDs ---");
        sb.AppendLine("Enum MenuID");
        sb.AppendLine("  miFirst = " + design.MenuEnumStart);
        foreach (var topMenu in design.MenuItems)
        {
            if (!string.IsNullOrEmpty(topMenu.EnumName))
                sb.AppendLine("  " + topMenu.EnumName);
            foreach (var child in topMenu.Children)
                if (!string.IsNullOrEmpty(child.EnumName))
                    sb.AppendLine("  " + child.EnumName);
        }
        sb.AppendLine("End Enum");
    }

    private static void EmitShortcutEnum(StringBuilder sb, W9FormDesign design)
    {
        sb.AppendLine("' --- Shortcut IDs ---");
        sb.AppendLine("Enum ShortCutID");
        sb.AppendLine("  siFirst = " + design.ShortcutEnumStart);
        sb.AppendLine("  siDefKey");
        sb.AppendLine("End Enum");
    }

    private static void EmitSharedVars(StringBuilder sb, W9FormDesign design)
    {
        sb.AppendLine("' --- Shared variables ---");
        sb.AppendLine("Dim Shared As HWND hMainForm");
        if (design.MenuItems.Count > 0)
        {
            sb.Append("Dim Shared As HMENU hMenu");
            foreach (var topMenu in design.MenuItems)
            {
                string varName = "h" + SanitizeVarName(topMenu.Text) + "Menu";
                sb.Append(", " + varName);
            }
            sb.AppendLine();
        }
        if (design.HasTimer)
            sb.AppendLine("Dim Shared As Integer Timer1");
    }

    private static void EmitEventHandlerStubs(StringBuilder sb, W9FormDesign design)
    {
        // Collect all gadgets that need event handlers
        var eventGadgets = new List<W9GadgetInstance>();
        foreach (var g in design.Gadgets)
        {
            if (g.GadgetType == W9GadgetType.Button)
                eventGadgets.Add(g);  // Buttons always get click handler
            else if (g.OnClickEvent || g.OnChangeEvent || g.OnDoubleClickEvent)
                eventGadgets.Add(g);
        }

        if (eventGadgets.Count == 0) return;

        sb.AppendLine("' ============================================================================");
        sb.AppendLine("' Event Handler Stubs - Add your code here");
        sb.AppendLine("' ============================================================================");
        sb.AppendLine();

        foreach (var g in eventGadgets)
        {
            string baseName = SanitizeVarName(g.EnumName.Replace("gi", ""));

            // OnClick handler (always for Buttons, opt-in for others)
            if (g.GadgetType == W9GadgetType.Button || g.OnClickEvent)
            {
                sb.AppendLine("Sub On" + baseName + "Click()");
                switch (g.GadgetType)
                {
                    case W9GadgetType.Button:
                        sb.AppendLine("    ' TODO: Handle " + g.EnumName + " click");
                        if (!string.IsNullOrEmpty(g.Text))
                            sb.AppendLine("    ' Button text: \"" + g.Text + "\"");
                        break;
                    case W9GadgetType.CheckBox:
                        sb.AppendLine("    ' TODO: Handle " + g.EnumName + " toggle");
                        sb.AppendLine("    Dim state As Integer = GetGadgetState(" + g.EnumName + ")");
                        sb.AppendLine("    ' state: 1 = checked, 0 = unchecked");
                        break;
                    case W9GadgetType.OptionButton:
                        sb.AppendLine("    ' TODO: Handle " + g.EnumName + " selection");
                        break;
                    case W9GadgetType.HyperLink:
                        sb.AppendLine("    ' TODO: Handle " + g.EnumName + " click");
                        break;
                    case W9GadgetType.TextLabel:
                        sb.AppendLine("    ' TODO: Handle " + g.EnumName + " click (requires SS_NOTIFY style)");
                        break;
                    default:
                        sb.AppendLine("    ' TODO: Handle " + g.EnumName + " click");
                        break;
                }
                sb.AppendLine("End Sub");
                sb.AppendLine();
            }

            // OnChange handler
            if (g.OnChangeEvent)
            {
                sb.AppendLine("Sub On" + baseName + "Change()");
                switch (g.GadgetType)
                {
                    case W9GadgetType.ComboBox:
                        sb.AppendLine("    ' TODO: Handle " + g.EnumName + " selection change");
                        sb.AppendLine("    Dim idx As Integer = GetGadgetState(" + g.EnumName + ")");
                        sb.AppendLine("    Dim txt As String = GetComboBoxText(" + g.EnumName + ")");
                        break;
                    case W9GadgetType.ListBox:
                        sb.AppendLine("    ' TODO: Handle " + g.EnumName + " selection change");
                        sb.AppendLine("    Dim idx As Integer = GetGadgetState(" + g.EnumName + ")");
                        sb.AppendLine("    Dim txt As String = GetListBoxText(" + g.EnumName + ", idx)");
                        break;
                    case W9GadgetType.Editor:
                        sb.AppendLine("    ' TODO: Handle " + g.EnumName + " text change");
                        sb.AppendLine("    ' Dim txt As String = GetGadgetText(" + g.EnumName + ")");
                        break;
                    case W9GadgetType.StringInput:
                        sb.AppendLine("    ' TODO: Handle " + g.EnumName + " text change");
                        sb.AppendLine("    Dim txt As String = GetGadgetText(" + g.EnumName + ")");
                        break;
                    case W9GadgetType.ScrollBar:
                    case W9GadgetType.TrackBar:
                    case W9GadgetType.SpinBox:
                        sb.AppendLine("    ' TODO: Handle " + g.EnumName + " value change");
                        sb.AppendLine("    Dim value As Integer = GetGadgetState(" + g.EnumName + ")");
                        break;
                    case W9GadgetType.Calendar:
                        sb.AppendLine("    ' TODO: Handle " + g.EnumName + " date selection");
                        break;
                    case W9GadgetType.PanelTab:
                        sb.AppendLine("    ' TODO: Handle " + g.EnumName + " tab change");
                        sb.AppendLine("    Dim tabIdx As Integer = GetGadgetState(" + g.EnumName + ")");
                        break;
                    default:
                        sb.AppendLine("    ' TODO: Handle " + g.EnumName + " change");
                        break;
                }
                sb.AppendLine("End Sub");
                sb.AppendLine();
            }

            // OnDoubleClick handler
            if (g.OnDoubleClickEvent)
            {
                sb.AppendLine("Sub On" + baseName + "DoubleClick()");
                switch (g.GadgetType)
                {
                    case W9GadgetType.ListBox:
                        sb.AppendLine("    ' TODO: Handle " + g.EnumName + " double-click");
                        sb.AppendLine("    Dim idx As Integer = GetGadgetState(" + g.EnumName + ")");
                        sb.AppendLine("    Dim txt As String = GetListBoxText(" + g.EnumName + ", idx)");
                        break;
                    case W9GadgetType.ListView:
                        sb.AppendLine("    ' TODO: Handle " + g.EnumName + " double-click");
                        sb.AppendLine("    ' Use EventNumberListView to get column info");
                        break;
                    case W9GadgetType.TreeView:
                        sb.AppendLine("    ' TODO: Handle " + g.EnumName + " double-click");
                        sb.AppendLine("    ' Use EventNumberTreeView to get item info");
                        break;
                    default:
                        sb.AppendLine("    ' TODO: Handle " + g.EnumName + " double-click");
                        break;
                }
                sb.AppendLine("End Sub");
                sb.AppendLine();
            }
        }
    }

    private static void EmitResizeHandler(StringBuilder sb, W9FormDesign design)
    {
        sb.AppendLine("' ============================================================================");
        sb.AppendLine("' size_change - Proportional resize of all gadgets");
        sb.AppendLine("' ============================================================================");
        sb.AppendLine("Sub size_change(WinWid As Long, WinHei As Long)");

        foreach (var g in design.Gadgets)
        {
            // StatusBar doesn't need resize (it auto-docks)
            if (g.GadgetType == W9GadgetType.StatusBar) continue;

            sb.AppendLine("  ResizeGadget(" + g.EnumName + ", ScaleX(" + g.X + "), ScaleY(" + g.Y + "), ScaleX(" + g.W + "), ScaleY(" + g.H + "))");

            // Re-apply special editor settings after resize
            if (g.GadgetType == W9GadgetType.Editor)
            {
                if (g.IsReadOnly) sb.AppendLine("  ReadOnlyEditor(" + g.EnumName + ", 1)");
                if (g.WordWrap) sb.AppendLine("  SetTransferTextLineEditorGadget(" + g.EnumName + ", 1)");
            }
        }

        // Font scaling
        sb.AppendLine();
        sb.AppendLine("  ' --- Scale fonts proportionally ---");
        foreach (var g in design.Gadgets)
        {
            if (g.GadgetType == W9GadgetType.StatusBar) continue;
            var tdef = W9GadgetRegistry.GetTypeDef(g.GadgetType);
            if (tdef != null && tdef.SupportsFont)
            {
                string fontName = string.IsNullOrEmpty(g.FontName) ? "Consolas" : g.FontName;
                int fontSize = g.FontSize > 0 ? g.FontSize : 11;
                sb.AppendLine("  SetGadgetFont(" + g.EnumName + ", Cint(LoadFont(\"" + fontName + "\", ScaleY(" + fontSize + "))))");
            }
        }

        sb.AppendLine();
        sb.AppendLine("  UpdateInfoXserver()");
        sb.AppendLine("End Sub");
    }

    private static void EmitMainSection(StringBuilder sb, W9FormDesign design)
    {
        sb.AppendLine("' ============================================================================");
        sb.AppendLine("' MAIN - Create window and gadgets");
        sb.AppendLine("' ============================================================================");
        sb.AppendLine();

        // Create window
        // Note: OpenWindow dimensions = outer window size.
        // Gadget coordinates are relative to the client area (below title bar).
        sb.AppendLine("' --- Create main window ---");
        sb.AppendLine("hMainForm = OpenWindow(\"" + EscapeString(design.FormTitle) + "\", " +
                      design.FormX + ", " + design.FormY + ", " +
                      design.FormWidth + ", " + design.FormHeight + ")");
        if (design.CenterOnScreen)
            sb.AppendLine("CenterWindow(hMainForm)");
        if (design.FormColor != Color.Empty)
            sb.AppendLine("WindowColor(hMainForm, BGR(" + design.FormColor.R + ", " +
                          design.FormColor.G + ", " + design.FormColor.B + "))");
        sb.AppendLine();

        // Create menus
        if (design.MenuItems.Count > 0)
        {
            EmitMenuCreation(sb, design);
            sb.AppendLine();
        }

        // Create gadgets
        sb.AppendLine("' --- Create gadgets ---");
        foreach (var g in design.Gadgets)
            EmitGadgetCreation(sb, g);
        sb.AppendLine();

        // Timer
        if (design.HasTimer)
        {
            sb.AppendLine("' --- Timer ---");
            sb.AppendLine("SetTimer(hMainForm, Timer1, " + design.TimerInterval + ", NULL)");
            sb.AppendLine();
        }

        // Keyboard shortcut
        if (design.HasKeyboardShortcut)
        {
            sb.AppendLine("' --- Keyboard shortcut (Enter key) ---");
            sb.AppendLine("AddKeyboardShortcut(hMainForm, FVIRTKEY, VK_RETURN, siDefKey)");
            sb.AppendLine();
        }

        sb.AppendLine("UpdateInfoXserver()");
        sb.AppendLine();

        // Force initial resize to fit actual client area
        if (design.ProportionalResize)
        {
            sb.AppendLine("' Force initial layout to fit actual client area");
            sb.AppendLine("size_change(WindowWidth(hMainForm), WindowHeight(hMainForm))");
        }
    }

    private static void EmitMenuCreation(StringBuilder sb, W9FormDesign design)
    {
        sb.AppendLine("' --- Create menu bar ---");
        sb.AppendLine("hMenu = Create_Menu()");
        foreach (var topMenu in design.MenuItems)
        {
            string varName = "h" + SanitizeVarName(topMenu.Text) + "Menu";
            sb.AppendLine(varName + " = MenuTitle(hMenu, \"" + EscapeString(topMenu.Text) + "\")");
            foreach (var child in topMenu.Children)
            {
                if (child.IsSeparator)
                    sb.AppendLine("    MenuItem(" + child.EnumName + ", " + varName + ", \"-\")");
                else
                    sb.AppendLine("    MenuItem(" + child.EnumName + ", " + varName + ", \"" + EscapeString(child.Text) + "\")");
            }
        }
    }

    private static void EmitGadgetCreation(StringBuilder sb, W9GadgetInstance g)
    {
        var tdef = W9GadgetRegistry.GetTypeDef(g.GadgetType);
        if (tdef is null) return;

        // Comment
        sb.AppendLine();
        sb.AppendLine("' --- " + tdef.DisplayName + ": " + g.EnumName + " ---");

        // Build the creation call based on gadget type
        switch (g.GadgetType)
        {
            case W9GadgetType.Button:
            {
                string style = string.IsNullOrEmpty(g.Style) ? "BS_DEFPUSHBUTTON" : g.Style;
                sb.AppendLine(tdef.W9FunctionName + "(" + g.EnumName + ", " +
                              g.X + ", " + g.Y + ", " + g.W + ", " + g.H + ", \"" +
                              EscapeString(g.Text) + "\", " + style + ")");
                break;
            }
            case W9GadgetType.TextLabel:
            {
                string style = string.IsNullOrEmpty(g.Style) ? "SS_NOTIFY" : g.Style;
                sb.AppendLine(tdef.W9FunctionName + "(" + g.EnumName + ", " +
                              g.X + ", " + g.Y + ", " + g.W + ", " + g.H + ", \"" +
                              EscapeString(g.Text) + "\", " + style + ")");
                break;
            }
            case W9GadgetType.Editor:
            {
                string edStyle = "ES_MULTILINE";
                if (g.HasVScroll) edStyle += " Or WS_VSCROLL";
                if (g.HasHScroll) edStyle += " Or WS_HSCROLL";
                sb.AppendLine(tdef.W9FunctionName + "(" + g.EnumName + ", " +
                              g.X + ", " + g.Y + ", " + g.W + ", " + g.H + ", \"" +
                              EscapeString(g.Text) + "\", " + edStyle + ")");
                if (g.IsReadOnly) sb.AppendLine("ReadOnlyEditor(" + g.EnumName + ", 1)");
                if (g.WordWrap) sb.AppendLine("SetTransferTextLineEditorGadget(" + g.EnumName + ", 1)");
                break;
            }
            case W9GadgetType.StringInput:
            {
                if (g.IsPassword)
                    sb.AppendLine(tdef.W9FunctionName + "(" + g.EnumName + ", " +
                                  g.X + ", " + g.Y + ", " + g.W + ", " + g.H + ", \"" +
                                  EscapeString(g.Text) + "\", ES_PASSWORD)");
                else
                    sb.AppendLine(tdef.W9FunctionName + "(" + g.EnumName + ", " +
                                  g.X + ", " + g.Y + ", " + g.W + ", " + g.H + ", \"" +
                                  EscapeString(g.Text) + "\")");
                break;
            }
            case W9GadgetType.CheckBox:
                sb.AppendLine(tdef.W9FunctionName + "(" + g.EnumName + ", " +
                              g.X + ", " + g.Y + ", " + g.W + ", " + g.H + ", \"" +
                              EscapeString(g.Text) + "\")");
                if (g.IsChecked) sb.AppendLine("SetGadgetState(" + g.EnumName + ", 1)");
                break;
            case W9GadgetType.OptionButton:
                sb.AppendLine(tdef.W9FunctionName + "(" + g.EnumName + ", " +
                              g.X + ", " + g.Y + ", " + g.W + ", " + g.H + ", \"" +
                              EscapeString(g.Text) + "\")");
                if (g.IsChecked) sb.AppendLine("SetGadgetState(" + g.EnumName + ", 1)");
                break;
            case W9GadgetType.ComboBox:
                sb.AppendLine(tdef.W9FunctionName + "(" + g.EnumName + ", " +
                              g.X + ", " + g.Y + ", " + g.W + ", " + g.H + ")");
                if (!string.IsNullOrEmpty(g.Items))
                    foreach (var item in g.Items.Split(LineSeparators, StringSplitOptions.RemoveEmptyEntries))
                        sb.AppendLine("AddComboBoxItem(" + g.EnumName + ", \"" + EscapeString(item.Trim()) + "\", -1)");
                break;
            case W9GadgetType.ListBox:
                sb.AppendLine(tdef.W9FunctionName + "(" + g.EnumName + ", " +
                              g.X + ", " + g.Y + ", " + g.W + ", " + g.H + ")");
                if (!string.IsNullOrEmpty(g.Items))
                    foreach (var item in g.Items.Split(LineSeparators, StringSplitOptions.RemoveEmptyEntries))
                        sb.AppendLine("AddListBoxItem(" + g.EnumName + ", \"" + EscapeString(item.Trim()) + "\")");
                break;
            case W9GadgetType.GroupBox:
                sb.AppendLine(tdef.W9FunctionName + "(" + g.EnumName + ", " +
                              g.X + ", " + g.Y + ", " + g.W + ", " + g.H + ", \"" +
                              EscapeString(g.Text) + "\")");
                break;
            case W9GadgetType.ImageBox:
                sb.AppendLine(tdef.W9FunctionName + "(" + g.EnumName + ", " +
                              g.X + ", " + g.Y + ", " + g.W + ", " + g.H + ")");
                if (!string.IsNullOrEmpty(g.ImagePath))
                {
                    sb.AppendLine("' TODO: Load image - Var hImg = Load_Image(\"" + EscapeString(g.ImagePath) + "\")");
                    sb.AppendLine("' SetImageGadget(" + g.EnumName + ", hImg)");
                }
                break;
            case W9GadgetType.ProgressBar:
                sb.AppendLine(tdef.W9FunctionName + "(" + g.EnumName + ", " +
                              g.X + ", " + g.Y + ", " + g.W + ", " + g.H + ", " +
                              g.MinValue + ", " + g.MaxValue + ")");
                if (g.CurrentValue > 0) sb.AppendLine("SetGadgetState(" + g.EnumName + ", " + g.CurrentValue + ")");
                break;
            case W9GadgetType.ScrollBar:
            {
                string style = g.Orientation == 1 ? "SB_VERT" : "SB_HORZ";
                sb.AppendLine(tdef.W9FunctionName + "(" + g.EnumName + ", " +
                              g.X + ", " + g.Y + ", " + g.W + ", " + g.H + ", " +
                              g.MinValue + ", " + g.MaxValue + ", " + style + ")");
                break;
            }
            case W9GadgetType.TrackBar:
                sb.AppendLine(tdef.W9FunctionName + "(" + g.EnumName + ", " +
                              g.X + ", " + g.Y + ", " + g.W + ", " + g.H + ", " +
                              g.MinValue + ", " + g.MaxValue + ")");
                if (g.CurrentValue > 0) sb.AppendLine("SetGadgetState(" + g.EnumName + ", " + g.CurrentValue + ")");
                break;
            case W9GadgetType.SpinBox:
                sb.AppendLine(tdef.W9FunctionName + "(" + g.EnumName + ", " +
                              g.X + ", " + g.Y + ", " + g.W + ", " + g.H + ", " +
                              g.MaxValue + ", " + g.MinValue + ", " + g.CurrentValue + ")");
                break;
            case W9GadgetType.TreeView:
            {
                string tvStyle = "";
                if (g.HasLines) tvStyle = "TVS_HASLINES Or TVS_LINESATROOT";
                if (g.HasButtons)
                    tvStyle = tvStyle == "" ? "TVS_HASBUTTONS" : tvStyle + " Or TVS_HASBUTTONS";
                if (g.HasCheckBoxes)
                    tvStyle = tvStyle == "" ? "TVS_CHECKBOXES" : tvStyle + " Or TVS_CHECKBOXES";
                if (tvStyle == "") tvStyle = "0";
                sb.AppendLine(tdef.W9FunctionName + "(" + g.EnumName + ", " +
                              g.X + ", " + g.Y + ", " + g.W + ", " + g.H + ", " +
                              tvStyle + ", WS_EX_CLIENTEDGE, 16)");
                break;
            }
            case W9GadgetType.ListView:
            {
                sb.AppendLine(tdef.W9FunctionName + "(" + g.EnumName + ", " +
                              g.X + ", " + g.Y + ", " + g.W + ", " + g.H + ")");
                for (int i = 0; i < g.ListViewColumns.Count; i++)
                    sb.AppendLine("AddListViewColumn(" + g.EnumName + ", \"" +
                                  EscapeString(g.ListViewColumns[i]) + "\", " + i + ", 120)");
                if (g.FullRowSelect || g.HasCheckBoxes)
                {
                    string exFlags = "";
                    if (g.FullRowSelect) exFlags = "LVS_EX_FULLROWSELECT";
                    if (g.HasCheckBoxes)
                        exFlags = exFlags == "" ? "LVS_EX_CHECKBOXES" : exFlags + " Or LVS_EX_CHECKBOXES";
                    sb.AppendLine("SetListViewExtendedStyle(" + g.EnumName + ", " + exFlags + ")");
                }
                break;
            }
            case W9GadgetType.StatusBar:
                sb.AppendLine(tdef.W9FunctionName + "(" + g.EnumName + ")");
                for (int i = 0; i < g.StatusBarFields.Count; i++)
                {
                    var sf = g.StatusBarFields[i];
                    sb.AppendLine("SetStatusBarField(" + g.EnumName + ", " + i + ", " +
                                  sf.Width + ", \"" + EscapeString(sf.Text) + "\")");
                }
                break;
            case W9GadgetType.PanelTab:
                sb.AppendLine(tdef.W9FunctionName + "(" + g.EnumName + ", " +
                              g.X + ", " + g.Y + ", " + g.W + ", " + g.H + ")");
                if (!string.IsNullOrEmpty(g.TabNames))
                {
                    var tabs = g.TabNames.Split(LineSeparators, StringSplitOptions.RemoveEmptyEntries);
                    for (int i = 0; i < tabs.Length; i++)
                        sb.AppendLine("Var hTab" + g.EnumName.Replace("gi", "") + i + " = AddPanelGadgetItem(" +
                                      g.EnumName + ", " + i + ", \"" + EscapeString(tabs[i].Trim()) + "\")");
                }
                break;
            case W9GadgetType.Container:
                sb.AppendLine(tdef.W9FunctionName + "(" + g.EnumName + ", " +
                              g.X + ", " + g.Y + ", " + g.W + ", " + g.H + ")");
                break;
            case W9GadgetType.Calendar:
                sb.AppendLine(tdef.W9FunctionName + "(" + g.EnumName + ", " +
                              g.X + ", " + g.Y + ", " + g.W + ", " + g.H + ")");
                break;
            case W9GadgetType.HyperLink:
                sb.AppendLine(tdef.W9FunctionName + "(" + g.EnumName + ", " +
                              g.X + ", " + g.Y + ", " + g.W + ", " + g.H + ", \"" +
                              EscapeString(g.Text) + "\")");
                break;
            default:
                sb.AppendLine("' Unsupported gadget type: " + g.GadgetType.ToString());
                break;
        }

        // Font — always set explicitly so gadgets have consistent appearance
        if (tdef.SupportsFont)
        {
            string fontName = string.IsNullOrEmpty(g.FontName) ? "Consolas" : g.FontName;
            int fontSize = g.FontSize > 0 ? g.FontSize : 11;
            sb.AppendLine("SetGadgetFont(" + g.EnumName + ", Cint(LoadFont(\"" + fontName + "\", " + fontSize + ")))");
        }

        // Colors
        if (g.BackColor != Color.Empty)
            sb.AppendLine("SetGadgetColor(" + g.EnumName + ", BGR(" +
                          g.BackColor.R + ", " + g.BackColor.G + ", " + g.BackColor.B + "), 0, 3)");
        if (g.ForeColor != Color.Empty)
            sb.AppendLine("SetGadgetColor(" + g.EnumName + ", BGR(" +
                          g.ForeColor.R + ", " + g.ForeColor.G + ", " + g.ForeColor.B + "), 1, 3)");

        // Tooltip
        if (!string.IsNullOrEmpty(g.Tooltip))
            sb.AppendLine("GadgetToolTip(" + g.EnumName + ", \"" + EscapeString(g.Tooltip) + "\")");

        // Enabled/Visible state
        if (!g.IsEnabled) sb.AppendLine("DisableGadget(" + g.EnumName + ", 1)");
        if (!g.IsVisible) sb.AppendLine("HideGadget(" + g.EnumName + ", 1)");
    }

    private static void EmitEventLoop(StringBuilder sb, W9FormDesign design)
    {
        sb.AppendLine("' ============================================================================");
        sb.AppendLine("' EVENT LOOP");
        sb.AppendLine("' ============================================================================");
        sb.AppendLine("Do");
        sb.AppendLine("    Select Case WaitEvent()");
        sb.AppendLine();

        // Resize event
        if (design.HandleResize && design.ProportionalResize)
        {
            sb.AppendLine("    Case EventSize");
            sb.AppendLine("        If EventHwnd = hMainForm Then");
            sb.AppendLine("            size_change(WindowWidth(hMainForm), WindowHeight(hMainForm))");
            sb.AppendLine("        End If");
            sb.AppendLine();
        }

        // Menu event
        if (design.MenuItems.Count > 0 || design.HasKeyboardShortcut)
        {
            sb.AppendLine("    Case EventMenu");
            sb.AppendLine("        Select Case EventNumber");
            if (design.HasKeyboardShortcut)
            {
                var defaultBtn = design.Gadgets.Find(g => g.ID == design.DefaultButtonID);
                if (defaultBtn != null)
                {
                    string handlerName = SanitizeVarName(defaultBtn.EnumName.Replace("gi", "On")) + "Click";
                    sb.AppendLine("        Case siDefKey");
                    sb.AppendLine("            " + handlerName + "()");
                }
                else
                {
                    sb.AppendLine("        Case siDefKey");
                    sb.AppendLine("            ' TODO: Handle Enter key");
                }
            }
            foreach (var topMenu in design.MenuItems)
                foreach (var child in topMenu.Children)
                    if (!child.IsSeparator)
                    {
                        sb.AppendLine("        Case " + child.EnumName);
                        sb.AppendLine("            ' TODO: Handle " + child.Text);
                    }
            sb.AppendLine("        End Select");
            sb.AppendLine();
        }

        // Timer event
        if (design.HasTimer)
        {
            sb.AppendLine("    Case EventTimer");
            sb.AppendLine("        ' TODO: Handle timer tick");
            sb.AppendLine();
        }

        // Close event
        sb.AppendLine("    Case EventClose");
        if (design.HasTimer)
            sb.AppendLine("        KillTimer(hMainForm, Timer1)");
        sb.AppendLine("        End");
        sb.AppendLine();

        // Gadget events (click, change, etc.)
        var clickGadgets = design.Gadgets.FindAll(g =>
            g.GadgetType == W9GadgetType.Button || g.OnClickEvent || g.OnChangeEvent || g.OnDoubleClickEvent);
        if (clickGadgets.Count > 0)
        {
            sb.AppendLine("    Case EventGadget");
            sb.AppendLine("        Select Case EventNumber");
            foreach (var g in clickGadgets)
            {
                string baseName = SanitizeVarName(g.EnumName.Replace("gi", ""));
                sb.AppendLine("        Case " + g.EnumName);

                if ((g.GadgetType == W9GadgetType.Button || g.OnClickEvent) && !g.OnChangeEvent && !g.OnDoubleClickEvent)
                    sb.AppendLine("            On" + baseName + "Click()");
                else if (g.OnClickEvent && g.OnChangeEvent)
                {
                    sb.AppendLine("            On" + baseName + "Click()");
                    sb.AppendLine("            On" + baseName + "Change()");
                }
                else if (g.OnChangeEvent && !g.OnClickEvent)
                    sb.AppendLine("            On" + baseName + "Change()");
                else if (g.GadgetType == W9GadgetType.Button)
                    sb.AppendLine("            On" + baseName + "Click()");

                if (g.OnDoubleClickEvent)
                {
                    sb.AppendLine("            ' Note: For double-click, check EventKey or use a timer");
                    sb.AppendLine("            ' On" + baseName + "DoubleClick()");
                }
            }
            sb.AppendLine("        End Select");
            sb.AppendLine();
        }

        sb.AppendLine("    End Select");
        sb.AppendLine("Loop");
    }

    // =========================================================================
    // Helpers
    // =========================================================================

    private static void EmitHelperReference(StringBuilder sb, W9FormDesign design)
    {
        // Build a list of which gadget types are used
        var usedTypes = new HashSet<W9GadgetType>();
        foreach (var g in design.Gadgets)
            usedTypes.Add(g.GadgetType);

        sb.AppendLine("' ============================================================================");
        sb.AppendLine("' Window9 API Quick Reference (for gadgets used in this form)");
        sb.AppendLine("' ============================================================================");

        // Common functions
        sb.AppendLine("' Common:");
        sb.AppendLine("'   GetGadgetText(gadgetID) -> String");
        sb.AppendLine("'   SetGadgetText(gadgetID, \"text\")");
        sb.AppendLine("'   GetGadgetState(gadgetID) -> Integer");
        sb.AppendLine("'   SetGadgetState(gadgetID, value)");
        sb.AppendLine("'   DisableGadget(gadgetID, 1)  /  DisableGadget(gadgetID, 0)");
        sb.AppendLine("'   HideGadget(gadgetID, 1)  /  HideGadget(gadgetID, 0)");
        sb.AppendLine("'   SetFocus(GadgetID(gadgetID))");
        sb.AppendLine("'   GadgetToolTip(gadgetID, \"tooltip text\")");
        sb.AppendLine("'   FreeGadget(gadgetID)");

        if (usedTypes.Contains(W9GadgetType.Editor))
        {
            sb.AppendLine("' Editor:");
            sb.AppendLine("'   GetGadgetText(id) -> full text  |  SetGadgetText(id, \"text\")");
            sb.AppendLine("'   GetLineTextEditor(id, lineNum) -> String");
            sb.AppendLine("'   GetLineCountEditor(id) -> Integer");
            sb.AppendLine("'   GetSelectTextEditorGadget(id) -> String");
            sb.AppendLine("'   GetModifyEditor(id) -> Integer (1=modified)");
            sb.AppendLine("'   PasteEditor(id)  |  ReadOnlyEditor(id, 1/0)");
            sb.AppendLine("'   SetTransferTextLineEditorGadget(id, 1) ' word wrap");
        }

        if (usedTypes.Contains(W9GadgetType.ComboBox))
        {
            sb.AppendLine("' ComboBox:");
            sb.AppendLine("'   AddComboBoxItem(id, \"text\", position)  ' -1 = end");
            sb.AppendLine("'   DeleteComboBoxItem(id, index)");
            sb.AppendLine("'   GetComboBoxText(id) -> String");
            sb.AppendLine("'   GetItemComboBox(id, index) -> String");
            sb.AppendLine("'   CountItemComboBox(id) -> Integer");
            sb.AppendLine("'   ResetAllComboBox(id)  ' clear all items");
            sb.AppendLine("'   SetComboBoxItemText(id, \"newtext\", index)");
        }

        if (usedTypes.Contains(W9GadgetType.ListBox))
        {
            sb.AppendLine("' ListBox:");
            sb.AppendLine("'   AddListBoxItem(id, \"text\")");
            sb.AppendLine("'   GetListBoxText(id, itemIndex) -> String");
            sb.AppendLine("'   GetItemListBox(id) -> Long (selected item index)");
            sb.AppendLine("'   CountItemListBox(id) -> Integer");
            sb.AppendLine("'   ResetAllListBox(id)  ' clear all items");
            sb.AppendLine("'   GetSelCountListBox(id) -> Integer (multi-select)");
        }

        if (usedTypes.Contains(W9GadgetType.ListView))
        {
            sb.AppendLine("' ListView:");
            sb.AppendLine("'   AddListViewColumn(id, \"header\", colIndex, width)");
            sb.AppendLine("'   AddListViewItem(id, \"text\", rowIndex)");
            sb.AppendLine("'   ReplaceTextColumnListView(id, \"text\", row, col)");
            sb.AppendLine("'   GetItemListView(id, row, col) -> String");
            sb.AppendLine("'   GetItemCountListView(id) -> Integer");
            sb.AppendLine("'   DeleteItemListView(id, row)");
        }

        if (usedTypes.Contains(W9GadgetType.TreeView))
        {
            sb.AppendLine("' TreeView:");
            sb.AppendLine("'   AddTreeViewItem(id, \"text\", img1, img2, pos)");
            sb.AppendLine("'   AddTreeViewItem(id, \"text\", img1, img2, pos, parentItem)");
            sb.AppendLine("'   GetItemTreeView(id) -> String (selected item text)");
            sb.AppendLine("'   GetCountItemTreeView(id) -> Integer");
            sb.AppendLine("'   RenameItemTreeView(id, \"newtext\")");
        }

        if (usedTypes.Contains(W9GadgetType.ProgressBar))
        {
            sb.AppendLine("' ProgressBar:");
            sb.AppendLine("'   SetGadgetState(id, value)  ' set position");
            sb.AppendLine("'   SetRangeProgressBar(id, min, max)");
        }

        if (usedTypes.Contains(W9GadgetType.ScrollBar) || usedTypes.Contains(W9GadgetType.TrackBar))
        {
            sb.AppendLine("' ScrollBar/TrackBar:");
            sb.AppendLine("'   GetGadgetState(id) -> Integer (current position)");
            sb.AppendLine("'   SetGadgetState(id, value)");
            sb.AppendLine("'   SetTrackBarMinPos(id, min)  |  SetTrackBarMaxPos(id, max)");
        }

        if (usedTypes.Contains(W9GadgetType.ImageBox))
        {
            sb.AppendLine("' Image:");
            sb.AppendLine("'   Var img = Load_Image(\"filename.bmp\")");
            sb.AppendLine("'   SetImageGadget(id, img)");
            sb.AppendLine("'   Resize_Image(img, newWidth, newHeight)");
            sb.AppendLine("'   Free_Image(img)");
        }

        if (usedTypes.Contains(W9GadgetType.PanelTab))
        {
            sb.AppendLine("' PanelTab:");
            sb.AppendLine("'   Var hTab = AddPanelGadgetItem(id, index, \"Tab Name\")");
            sb.AppendLine("'   UseGadgetList(hTab)  ' add gadgets to this tab");
            sb.AppendLine("'   GetGadgetState(id) -> Integer (selected tab index)");
        }

        if (usedTypes.Contains(W9GadgetType.StatusBar))
        {
            sb.AppendLine("' StatusBar:");
            sb.AppendLine("'   SetStatusBarField(id, fieldIndex, width, \"text\")");
        }

        sb.AppendLine("' Dialogs:");
        sb.AppendLine("'   OpenFileRequester(\"Title\", startDir, \"Filter|*.ext|\") -> String");
        sb.AppendLine("'   SaveFileRequester(\"Title\", startDir, \"Filter|*.ext|\") -> String");
        sb.AppendLine("'   ColorRequester(defaultColor) -> Long");
        sb.AppendLine("'   MessageRequester(\"Title\", \"Message\", flags) -> Integer");
        sb.AppendLine("'   InputRequester(\"Title\", \"Prompt\", \"Default\") -> String");
    }

    private static string EscapeString(string? s)
    {
        if (s is null) return "";
        // FreeBASIC string escaping: double embedded quotes, drop CR, turn LF into
        // a literal `" + Chr(10) + "` so multi-line text stays valid in source.
        return s.Replace("\"", "\"\"").Replace("\r", "").Replace("\n", "\" + Chr(10) + \"");
    }

    private static string SanitizeVarName(string? s)
    {
        if (s is null) return "Unknown";
        var result = new StringBuilder();
        foreach (var c in s)
            if (char.IsLetterOrDigit(c))
                result.Append(c);
        if (result.Length == 0) return "Unknown";
        return result.ToString();
    }

    private static string SanitizeFilename(string? s)
    {
        if (s is null) return "untitled";
        var result = new StringBuilder();
        foreach (var c in s)
        {
            if (char.IsLetterOrDigit(c) || c == '_' || c == '-')
                result.Append(c);
            else if (c == ' ')
                result.Append('_');
        }
        if (result.Length == 0) return "untitled";
        return result.ToString().ToLower();
    }
}
